### ISSUE TITLE
Angular2@latest

### ISSUE THREAD

**Issue by kuncevic** [cmelion/ng2-webpack-demo-app#2]
Any reasons it is referencing Angular2 2.0.0-beta.8 ?

**Comment by cmelion** [comment]
Certain features can cause minification to break and need to be explicitly excluded when mangling is turned on ([RouterLink](https://github.com/angular/angular/issues/6678) is one such feature).

```
 +                mangle: {
 +                    screw_ie8 : true,
 +                    except: ['RouterLink'] // needed for uglify RouterLink problem
 +                },// prod
```

Beta.8 is the last version I tested and is confirmed as working with the above webpack config.

You can change to @latest in the generated projects package.json and re-run npm install for now.

**Comment by cmelion** [comment]
I bumped the demo and the generator up to Beta.9.  No issues.
The generator has been re-published.

`npm update generator-ng2-webpack`

This would also make a simple test case for re-running:
`yo ng2-webpack`

I'm running Webstorm so my preferred method of updating generated projects is to select 'a' for all and just overwrite everything without further prompts and view local-history on the top-level folder.  I find it easier to select  just the files I care about, from the changed files list, one at a time and do a visual diff.
